import { collection, doc, limit, onSnapshot, orderBy, query, where } from 'firebase/firestore';
import { getFirestore } from 'firebase/firestore';
import { callFunction } from '../firebaseApi.web';
import type { ConnectionMember, ConnectionRequest, Conversation, DirectMessage, FeedItem, SocialPost } from '../types/social';
const db = getFirestore();
export const createConnectionRequest = (targetUid: string) => callFunction<{ targetUid: string }, { ok: boolean; requestId: string }>('createConnectionRequest', { targetUid });
export const respondToConnectionRequest = (requestId: string, decision: 'accept' | 'decline') => callFunction<{ requestId: string; decision: 'accept' | 'decline' }, { ok: boolean }>('respondToConnectionRequest', { requestId, decision });
export const createPost = (body: string) => callFunction<{ body: string }, { ok: boolean; postId: string }>('createPost', { body });
export const reactToPost = (postId: string, reaction: 'like' | 'celebrate' | 'insightful') => callFunction<{ postId: string; reaction: string }, { ok: boolean; active: boolean }>('reactToPost', { postId, reaction });
export const commentOnPost = (postId: string, body: string) => callFunction<{ postId: string; body: string }, { ok: boolean; commentId: string }>('commentOnPost', { postId, body });
export const sendDirectMessage = (targetUid: string, body: string) => callFunction<{ targetUid: string; body: string }, { ok: boolean; conversationId: string; messageId: string }>('sendDirectMessage', { targetUid, body });
export const reportContent = (input: { contentType: 'post' | 'comment' | 'profile'; contentId: string; reason: string; parentId?: string }) => callFunction<typeof input, { ok: boolean; flagId: string; alreadyReported: boolean }>('reportContent', input);
export function subscribeConnections(uid: string, onNext: (items: ConnectionMember[]) => void, onError: (error: Error) => void): () => void { return onSnapshot(collection(doc(collection(db, 'connections'), uid), 'members'), (s) => onNext(s.docs.map(d => ({ uid: d.id, ...d.data() })) as ConnectionMember[]), onError); }
export function subscribeIncomingRequests(uid: string, onNext: (items: ConnectionRequest[]) => void, onError: (error: Error) => void): () => void { const q = query(collection(db,'connection_requests'), where('toUid','==',uid), where('status','==','pending'), orderBy('createdAt','desc'), limit(50)); return onSnapshot(q,s=>onNext(s.docs.map(d=>({id:d.id,...d.data()})) as ConnectionRequest[]),onError); }
export function subscribeFeed(uid: string, onNext: (items: FeedItem[]) => void, onError: (error: Error) => void): () => void { const q=query(collection(doc(collection(db,'feeds'),uid),'items'),orderBy('score','desc'),limit(50)); return onSnapshot(q,s=>onNext(s.docs.map(d=>({id:d.id,...d.data()})) as FeedItem[]),onError); }
export function subscribePosts(ids: string[], onNext: (posts: SocialPost[]) => void, onError: (error: Error) => void): () => void { if(!ids.length){onNext([]);return()=>undefined;} const q=query(collection(db,'posts'),where('__name__','in',Array.from(new Set(ids)).slice(0,30))); return onSnapshot(q,s=>onNext(s.docs.map(d=>({id:d.id,...d.data()})) as SocialPost[]),onError); }
export function subscribeConversations(uid: string, onNext: (items: Conversation[]) => void, onError: (error: Error) => void): () => void { const q=query(collection(db,'conversations'),where('memberUids','array-contains',uid),orderBy('updatedAt','desc'),limit(50)); return onSnapshot(q,s=>onNext(s.docs.map(d=>({id:d.id,...d.data()})) as Conversation[]),onError); }
export function subscribeMessages(conversationId: string, onNext: (items: DirectMessage[]) => void, onError: (error: Error) => void): () => void { const q=query(collection(doc(collection(db,'conversations'),conversationId),'messages'),orderBy('createdAt','asc'),limit(100)); return onSnapshot(q,s=>onNext(s.docs.map(d=>({id:d.id,...d.data()})) as DirectMessage[]),onError); }
