import React, { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Alert, FlatList, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { getAdminAnalytics } from '../../analyticsService';
import { callFunction } from '../../firebaseApi';
import type { AdminAnalytics } from '../../types/analytics';
import type { UserProfile, UserRole } from '../../types/auth';
interface AdminUser extends UserProfile { accountStatus?: 'active'|'suspended'|'revoked'; }
interface UserResponse { users: AdminUser[]; }
const roles: Array<'all'|UserRole> = ['all','student','alumni','business','administrator'];
const statuses = ['all','active','suspended','revoked'] as const;
export function AdminDashboardScreen() {
 const [analytics,setAnalytics]=useState<AdminAnalytics|null>(null); const [users,setUsers]=useState<AdminUser[]>([]); const [role,setRole]=useState<'all'|UserRole>('all'); const [status,setStatus]=useState<typeof statuses[number]>('all'); const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false); const [error,setError]=useState('');
 const load=useCallback(async()=>{try{setError('');const [a,u]=await Promise.all([getAdminAnalytics(),callFunction<{role:string;status:string},UserResponse>('listAdminUsers',{role,status})]);setAnalytics(a);setUsers(u.users);}catch(e){setError(e instanceof Error?e.message:'Unable to load administrator data.');}finally{setLoading(false);setRefreshing(false);}},[role,status]);
 useEffect(()=>{void load();},[load]);
 const setUserStatus=(user:AdminUser,next:'active'|'suspended'|'revoked')=>Alert.alert('Confirm account change',`${user.displayName||user.email} will be ${next}.`,[{text:'Cancel',style:'cancel'},{text:'Confirm',style:next==='revoked'?'destructive':'default',onPress:async()=>{try{await callFunction('manageUserStatus',{uid:user.uid,status:next});await load();}catch(e){Alert.alert('Failed',e instanceof Error?e.message:'Unable to update account.');}}}]);
 if(loading)return <ActivityIndicator style={{flex:1}} size="large"/>;
 return <FlatList data={users} keyExtractor={u=>u.uid} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);void load();}}/>} contentContainerStyle={styles.list} ListHeaderComponent={<><Text style={styles.title}>Administrator Control Centre</Text><Text style={styles.sub}>Lifecycle management, platform analytics and security operations.</Text>{error?<Text style={styles.error}>{error}</Text>:null}{analytics?<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.metrics}>{[['Users',analytics.totalUsers],['Active 30d',analytics.activeUsers30d],['New 30d',analytics.newRegistrations30d],['Pending business',analytics.pendingBusinessApprovals],['Open flags',analytics.flaggedContent]].map(([l,v])=><View key={String(l)} style={styles.metric}><Text style={styles.metricValue}>{String(v)}</Text><Text>{String(l)}</Text></View>)}</ScrollView>:null}<Text style={styles.heading}>Users</Text><ScrollView horizontal contentContainerStyle={styles.filters}>{roles.map(r=><Pressable key={r} onPress={()=>setRole(r)} style={[styles.filter,role===r&&styles.selected]}><Text style={role===r?styles.selectedText:undefined}>{r}</Text></Pressable>)}</ScrollView><ScrollView horizontal contentContainerStyle={styles.filters}>{statuses.map(s=><Pressable key={s} onPress={()=>setStatus(s)} style={[styles.filter,status===s&&styles.selected]}><Text style={status===s?styles.selectedText:undefined}>{s}</Text></Pressable>)}</ScrollView></>} renderItem={({item})=><View style={styles.card}><View style={{flex:1}}><Text style={styles.name}>{item.displayName||item.email}</Text><Text>{item.email}</Text><Text style={styles.meta}>{item.role} · {item.accountStatus||'active'}</Text>{item.companyName?<Text>{item.companyName}</Text>:null}</View>{item.role!=='administrator'?<View style={styles.actions}>{item.accountStatus==='active'?<Pressable style={styles.action} onPress={()=>setUserStatus(item,'suspended')}><Text style={styles.white}>Suspend</Text></Pressable>:<Pressable style={styles.action} onPress={()=>setUserStatus(item,'active')}><Text style={styles.white}>Activate</Text></Pressable>}<Pressable style={styles.danger} onPress={()=>setUserStatus(item,'revoked')}><Text style={styles.white}>Revoke</Text></Pressable></View>:<Text style={styles.meta}>Protected administrator</Text>}</View>} ListEmptyComponent={<Text style={styles.empty}>No users match these filters.</Text>}/>;
}
const styles=StyleSheet.create({list:{padding:16,paddingBottom:40},title:{fontSize:28,fontWeight:'800'},sub:{color:'#667085',marginBottom:16},error:{color:'#b42318',marginBottom:12},metrics:{gap:10,paddingBottom:18},metric:{width:125,padding:14,borderRadius:14,backgroundColor:'#f2f4f7'},metricValue:{fontSize:24,fontWeight:'800'},heading:{fontSize:20,fontWeight:'800',marginBottom:8},filters:{gap:8,paddingBottom:9},filter:{paddingHorizontal:13,paddingVertical:8,borderRadius:20,borderWidth:1,borderColor:'#d0d5dd'},selected:{backgroundColor:'#111827'},selectedText:{color:'#fff'},card:{padding:14,borderRadius:14,borderWidth:1,borderColor:'#e4e7ec',marginBottom:10,flexDirection:'row',gap:10},name:{fontSize:16,fontWeight:'800'},meta:{color:'#667085',marginTop:3},actions:{justifyContent:'center',gap:6},action:{backgroundColor:'#111827',paddingHorizontal:10,paddingVertical:8,borderRadius:8},danger:{backgroundColor:'#b42318',paddingHorizontal:10,paddingVertical:8,borderRadius:8},white:{color:'#fff',fontWeight:'700'},empty:{textAlign:'center',padding:30,color:'#667085'}});
